/*
   Mitra TOKEN

   This contract creates token based on
   the energy generated by the solar panel
*/

pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";


contract Mitra is usingOraclize{
  address public creator;
  mapping (address => uint) public balances;
  bytes32 energyValue;

  event newOraclizeQuery(string description);
//  event newEnergyValue(string energyValue);

  //event that notifies when a transfer has completed
  event Delivered(address from, address to, uint amount);

  function Mitra(){
    creator = msg.sender ;
  }

  function create(address receiver) payable{
    if (msg.sender != creator) throw;

    newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
    energyValue = oraclize_query("URL", "xml(https://www.fueleconomy.gov/ws/rest/fuelprices).fuelPrices.electric");
    balances[receiver] += uint(energyValue);
  }

  function transfer(address receiver, uint amount){
    if (balances[msg.sender]< amount) throw;
    balances[msg.sender] -= amount;
    balances[receiver] += amount;
    Delivered(msg.sender, receiver, amount);
  }
}
